name: CI Plazza

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**f'

env:
  EXECUTABLES: plazza
  MIRROR_URL: git@github.com:EpitechPromo2027/B-CCP-400-NAN-4-1-theplazza-alban.peralta.git

jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: make verify
        run: make
      - name: make clean
        run: make clean
      - name: execute
        run: |
          if [ -x ${{ env.EXECUTABLES }} ]; then
            echo "Executable file exists"
          else
            echo "Executable file does not exist"
            exit 1
          fi

  Repository_Mirroring:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}

  run_tests:
    runs-on: ubuntu-latest
    needs: check_program_compilation
    container:  epitechcontent/epitest-docker
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: make test
        run: make tests_run
